version: '3.8'

services:
  webserver:
    build:
      context: .
      dockerfile: .docker/Nginx.Dockerfile
    ports:
      - 80:80
    volumes:
      - ./:/var/www/laravel

  app:
    build:
      context: .
      dockerfile: .docker/Fpm.Dockerfile
    volumes:
      - ./:/var/www/laravel
